### PR TITLE
Multirom support

### PR DESCRIPTION
**Pull request by chastai**
Hi,

I've started to implement support for multiple ROMs in ems-flasher. There is room for improvement but it is functional. You can insert/delete/remove ROMs. The incremental defragmenter is working too and well tested.
I've reused some Awk scripts (insert.awk and update.awk) from the prototype that I call from C with popen()
but I could rewrite them in C later.

Compilation:
 1. Install RGBDS (https://github.com/bentley/rgbds)
 2. Update the menu submodule: git submodule init && git submodule update
 3. Compile with make MENUDIR=. LIBEXECDIR=. to be able to test it without installation
 4. You may also run tests.sh to test the Awk scripts.

Commands:
 --title:
Print the listing of the page selected by --bank.
The starting bank number (a bank is 16K) is indicated for each ROM (see --delete).

Maybe it would be more appropriate to rename --title in --list?
By the way, I think --bank should  be renamed in --page.

--delete:
Accept a list of banks corresponding to the ROMs to delete.
Currently, it doesn't check if the bank belong to the selected page (it ignores --bank)
 
I've choosed to use bank numbers instead of indexes to limit the chance that references to ROMs change between two invokations of ems-flasher. So the user can invoke ems-flasher --title and then delete ROMs in multiple steps without risk (unless he adds new ROMs and defragmentation is needed).

We could add the possibility to delete ROMs by name

--format:
Delete all ROMs of the selected page

--write:
 * It now  accepts multiple files as arguments.
 * A menu is added when ROMs are inserted to an empty page. The features/enhancements bits (color, sgb) are copied from the first ROM.
 * It doesn't check if the added ROMs have exactly the same features enabled as the menu (this information is available with --title though). We should check that as a game may no work properly otherwise. But we could be less strict if we knew the target hardware. By example if the user has no SGB, it could mix SGB enhanced ROM with classic ROMs.
 * It doesn't warn the user if no menu was found (but it should) and allow insertion of new ROM.
 * It doesn't check for title duplicates.
 * The romsize code of a ROM must match the file size. We could be less strict by allowing the file to be smaller or, better by correcting the romsize code field on the fly when necessary.
 * When flashing a file it doesn't check if the file has changed since the time the file was first read to get its header and size. We could check that or load the file in memory when first accessed.

Improvements:
 * Add a progress bar
 * implement --read
 * When flashing a ROM, we could write the last bytes of the header last so the ROM would not be valid until all bytes have been effectively flashed.
 * Prevent the software to be interrupted in critical parts where it would block the card (requiring the user to reconnect the device). By example, in the middle of a USB transfer.

The file Tech has some information about the device USB programming.
The menu is developed there : https://github.com/chastai/menugb

Of course I will continue to work on this. Any comments/critics are welcome.

Christophe.

### CODE REVIEW

**Comment by mikeryan** [comment]
This is a sizable body of work. It looks very nice, thank you for your outstanding contribution!

I have misplaced my cart so I can't test directly, but from what I read above it all makes sense. My only concern with renaming --bank to --page is that it will break compatibility with existing users.

I see some minor issues with the menu folder. First, if the submodule is not checked out the behavior is a bit user-hostile:

```
make[1]: Entering directory `.../ems-flasher/menu'
make[1]: *** No targets specified and no makefile found.  Stop.
```

I also don't want ordinary users to have to install rgbds to build the menu. We should make the build scripts a bit smarter and:

1. do the Right Thing when the submodule is not checked out
2. ship a menu.gb that works for 99% of everyone
I don't want to force users to download rgbds to build the menu if we can avoid it. Can we ship a compiled menu.gb and have the build scripts intelligently detect

**Comment by chastai** [comment]
You're welcome.

The hardest part was the development of the defragmenter. I found the right algorithm intuitively at the first attempt but I was not sure that it was correct. So I put into practice this adage of Ken Thompson: "When in doubt, use brute force." and I created a script to generate fragmented images randomly to test the algorithm to prove than, at least, I was following the right direction. Eventualy, the penny has dropped and after two rewrites it was ready to going public.

For the problems with the dependency to RGBDS and with the submodule:
We could provide the menu.gb binary in the root directory. The other versions of the menu (with different headers for color/sgb enhancements...) could be built automatically by a portable shell script (with awk and od) to avoid invoking rgbfix. This will also allow the user to use a different menu simply by replacing menu.gb.

So, when the user invoke make alone, menu.gb is left untouched. make stockmenu (by example) will ensure that ems-flasher is compiled with the stock menu.gb binary (the original menu.gb will be restored from a file). make menugb will compile ems-flasher with the specified menu program (and menu.gb will be overwritten). The script will ask the user to invoke the adequate git commands when the menu subdirectory is empty. Of course, we could also detect the presence of RGBDS. Or we could even write a Game Boy assembler in Awk :-)
We could also replace the submodule by incorporating the menu repository with a subtree merge.
Also, I would rename the menu directory by menugb as menu.gb is a menu software among others. 

Christophe.

**Comment by mikeryan** [comment]
I'm happy to leave the menu as a separate repository. We should use different Makefile targets for using built-in menus or rebuilding the menu from source. I'd like the default behavior (just running ```make```) to be sensible, preferably using the menu designed for color/b&w.

**Comment by chastai** [comment]
I've work a bit on it this weekend:
* I've made a special version of ems-flasher which operates on a file so you can test it without the actual cartridge.
You can build it with make ems-flasher-file. By default the image file is image.gb but you can change it by exporting the IMAGEFILE environment variable.
This version doesn't support operations on SRAM yet.
The image combines both pages. You can use split -n2 to split it in two files and use them with an emulator supporting EMS smartcard page images like BGB (works well with Wine).

* I've added two rules to ease compilation of development versions in Makefile:
ems-flasher-dev and ems-flasher-file-dev build both versions of ems-flasher with MENUDIR=. and LIBEXECDIR=. so they can be tested without installation.

* I've added a precompiled version of the menu and changed Makefile this way:
  check-menu: it builds the variants of the menu (color/super/color+super) from menu.gb.
  menu.gb: check if menu.gb exists and inform the user of how to install it if not. menu.gb is present in the repo.
  menu-orig: copy menu.gb.orig to menu.gb to restore the precompiled menu.
  menu: make the menu from source and instruct the user how to update the submodule if necessary.

* I've started to implement the display of a progression status.

I'll try to work on other details this week. Of course, once merged, feel free to change anything to your taste.

Christophe.

**Comment by chastai** [comment]
```
Hello,

Here are the important things I've done since the last time :
 - converted the insert/update awk scripts executed by the program to C
   functions
 - terminate cleanly when a --write operation is interrupted by a signal
 - show the estimated time left in the progression status
 - on write and move operations, the integrity of flashed ROMs is guaranteed by
   keeping the header invalid until the last write operation. When moving a ROM
   (defragmenting), the source ROM is deleted after the copy is successful.
 - the menu switches the palette to grey instead of the default dark green on
   a Game Boy Color when running a Classic Game Boy ROM.

Important things that remain to be done:
 - if libusb is multithreaded (it concerns at least the versions with the
   hotplug feature on Linux and Mac), we must ensure that the signals are
   blocked in all threads except the main thread.
 - signals (at least SIGHUP/SIGINT/SIGTERM) must be blocked during flash
   I/O operations in cmd_title(), cmd_delete(), cmd_format(), cmd_title()
   and cmd_write() (for the call to list()).
 - define a time out for I/O operations
 - --read individual ROMs
 - a command to update the menu
 - handling the compatibility of the hardware enhancements of ROMs in the same
   page.
 - ...

I will add some unit tests later.

The menu is precompiled in menu.gb (compat mode).
Use make check-menu to create the variants (color/sgb/color+sgb headers).

make ems-flasher-dev will compile a version that uses the menus in the current
directory.
make ems-flasher-file-dev will compile a version using a file (image.gb) in
place of the real cartridge.

Random notes:

--title (cmd_title()):

 - The title of the menu ROM is now "MENU#" and the publisher is Nintendo (this
   combination allows the grey palette to be selected (the checksum of the title
   matches the one of the game "X"). The title of the menu from EMS is "GB16M".

 - Title of ROMs: the Nintendo ASCII character set is used (64 characters, it
   lacks lowercases by example), unknow characters are replaced by a space. EMS
   uses an extended ASCII character set.

 - ROM listing (list()):
   This version is quite naive and skips the ROMs that are misaligned or whose
   the size declared in the header is not a power of two or is wrongly coded as
   these ROMs would make the degragmentation algorithm crazy (note that to my
   knowledge the only ROMs not a power of two are firmware ROMs for the camera
   or other extensions).
   This means that these "faulty" ROMs could be overwritten as list() is also
   used by --write.
   I think we should warn the user if one of these problems should occur and
   simply forbid any change until the problems are solved: i.e. by deleting the
   ROM. The user could possibly --read the faulty ROM before that.

 - Hardware enhancements: these are defined in the menu ROM header and apply
   to all ROMs of the page. There are four modes:
   - DMG exclusive: emulate the behaviours of the Classic Game Boy when run
     on a Game Boy Color (notably regarding the sprite overlapping rules,
     the palette, ...).
   - DMG/CGB compatible: enable extended features when run on a Color Game
     Boy (the program will take the differences between a DMG and a CGB
     into account).
   - CGB exclusive: not enforced by the hardware. Normally, the program will
      display an error message if run on a DMG.
   - SGB: enable SGB features on a SGB.

     DMG exclusive and DMG/CGB compatible are mutually exclusive.
     CGB exclusive is technically equivalent to DMG/CGB compatible.

    Problems would arise if
      - a CGB ROM ran on a CGB in DMG exclusive mode.
      - a DMG ROM ran on a CGB in DMG/CGB compatible mode.
         (different rules for sprite overlapping, ...)
      - a SGB ROM ran on a SGB in non SGB mode
          (it is possible that the program would backup to DMG functionalities
           if it can't detect the SGB)
      - a DMG or CGB ROM ran on a SGB in SGB mode.
         (this is perhaps less problematic. The only risk is if the program use
          the addresses of the mapped ports).

 This version of --list displays the modes set in the header of each ROM and the
 actual one.

--delete
   I've used the term "bank" to designate a ROM location, that could be confusing as
   this word is used to designate a page elsewhere.

--write:

    - At start, the headers of the ROM files are read, but the data are loaded
      only when the ROM is flashed. It uses the ctime to see if a file has not
      been modified since the header was read. I don't remember why I did that
      like that but may be it would be easier to load the entire files at start.

    - The size in the header must match the file size. Maybe it's too strict? considering
      that this parameter is not checked by the hardware). Instead, the size could be
      adjusted on the fly when it doesn't match. 
      Also we could allow the file to be smaller (when the ROM has not be
      padded).

    - A menu is always present even when the ROM is isolated on a page (excepted
      for 4 MB ROMs) so that the grey palette is selected when run on CGB
      whether there is one or more ROMs (in fact, it's only necessary for DMG
      ROM).
      Also, we should propose a --no-menu option. Of course, only one ROM could
      be written in this case.
      Note that the menu software will launch the ROM directly if the ROM is
      isolated.  

    - Compatibility of hardware enhancements: no check is made to see if the
      ROMs added are compatible with the header of the menu.
      The enhancments written in the header of the menu are determined by the
      first ROM added.

      We could simply prevent the user from mixing ROMs with incompatible settings
      but if, e.g. he has specified that he doesn't own a SGB, we could then
      ignore the SGB enhancement flag and allow mixing of SGB and non SGB ROMs on a
      same page or if the user state that it doesn't own a CGB, it could mix
      CGB and DMG games... The user choice could be stored in the menu by
      example.

    - Compatibility with EMS:
        - all ROMs flashed by the EMS software are visible by our software.
        - the EMS software expects the ROMs to be sorted by size in ascending
          order so some ROMs created by ems-flasher won't be visible by their
          software.
        When we detect a cartridge created with EMS software (the title of the
        menu is "GB16M"), we should not allow any change until the user has
        changed the menu software.
       And by the way, there should be a command to update/set the menu.

That's all for now.

Feel free to keep/remove/rearange the code like you want.

Christophe.
```

**Comment by mikeryan** [comment]
Hey Christophe, is there anything else you'd like to add to this? I will merge the pull request if I don't hear back in a few days.

Thanks as always for your fine work on this!

**Pull request merged**
